apiVersion: v1
kind: ConfigMap
metadata:
  name: ens-config
  namespace: ens
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/NotificationSystem"
  # Фронту может понадобиться публичный API URL за Ingress:
  PUBLIC_API_URL: "http://ens.local/api"
  # Kafka bootstrap внутри кластера:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
---
apiVersion: v1
kind: Secret
metadata:
  name: ens-secrets
  namespace: ens
type: Opaque
data:
  POSTGRES_DB: Tm90aWZpY2F0aW9uU3lzdGVt
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4=
  # Если хочешь — добавь сюда JWT и другие секреты, которые юзает бэкенд.
